language: python

env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.8

python:
  - 2.7
  - 3.6

install:
  - pip install Django==${DJANGO_VERSION}

script:
  - ./manage.py test
