language: python

env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.8

python:
  - 2.7
  - 3.6

matrix:
  exclude:
    - env: DJANGO_VERSION=2.0
      python: 2.7

install:
  - pip install Django==${DJANGO_VERSION}
  - if [[ $TRAVIS_PYTHON_VERSION == 2.* ]]; then pip install mock; fi
  - pip install flake8

script:
  - ./manage.py test
  - flake8 user_language_middleware tests
